### ISSUE TITLE
Query: subscribe is not a function.

### ISSUE THREAD

**Issue by mananjadhav** [senecajs/seneca-pubsub#5]
Hi,
I am trying to run use this plugin but it gives me following error:

```
seneca.subscribe({role: 'foo'}, function (msg) {
       ^

TypeError: seneca.subscribe is not a function
    at Object.<anonymous> (C:\Project\Creanara\src\backend\services\authservice\test\example.js:5:8)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
    at startup (node.js:141:18)
    at node.js:980:3

```

I am trying to run the following basic example and I have seneca and seneca-pubusb installed.

Earlier I had seneca 0.7 and learnt that decorator support was added after 0.9. Is there anything else that has to be done to get it working?
My seneca version is 1.3 and seneca-pubsub is 0.1.0

```
var seneca = require('seneca')()
seneca.use(require('seneca-pubsub'))

seneca.subscribe({role: 'foo'}, function (msg) {
    console.log("F1");
    console.log(msg.data.value);    
})
seneca.subscribe({role: 'foo'}, function (msg) {
    console.log("F2");
    console.log(msg.data.value);    
})
seneca.publish({role: 'foo', data: {value: 10}})
seneca.publish({role: 'foo', data: {value: 20}})
seneca.publish({role: 'foo', data: {value: 30}})
```

**Comment by mcdonnelldean** [comment]
Odd, it should work. Let me pull it down later this evening and see what's up

**Comment by mananjadhav** [comment]
I was trying around all the different possibilities. If I paste your complete code in my snippet along with seneca, it works. But if I try and use it as _require('seneca-pubsub')_  it doesn't work.

Following is what I tried and it worked.

```
var Varo = require('varo')
var varo
var seneca = require('seneca')()
options = {}

var defaults = {
  indexing: 'depth'
}

var extend = seneca.util.deepextend

options = extend(defaults, options)

varo = options.varo || new Varo(options)

seneca.decorate('subscribe', varo.observe.bind(varo))
seneca.decorate('publish', varo.emit.bind(varo))

console.log(seneca._decorations)
seneca.subscribe({role: 'foo'}, function (msg) {
    console.log("F1",msg.data.value + 1)
    console.log("\n")    
})

seneca.subscribe({role: 'foo'}, function (msg) {
    console.log("F1",msg.data.value)
    console.log("\n")     
})

seneca.publish({role: 'foo', data: {value: 10}})
seneca.publish({role: 'foo', data: {value: 20}})
seneca.publish({role: 'foo', data: {value: 30}})
```

And if I use this snippet and still use require('seneca-pubsub'), it says _seneca is already decorated with the property._

Would be great if you can help with this.

**Comment by mananjadhav** [comment]
Just to add, I also tried `fire-and-forget`, because it uses decoration. Same issue. 

You think this could be due to some problem with seneca core in terms of handling decorators defined inside the plugins?

**Comment by mcdonnelldean** [comment]
@MananJ Yup, I have a sneaking suspicion something in the decoration mech itself is broken. I'll run through some tests tonight and update the code.

**Comment by mananjadhav** [comment]
Thanks a lot for checking this.

I had one more question. Does this pubsub works only locally? 

If I put use seneca with {host,port}, and emit/observe it doesn't work. If I use locally it works.

**Comment by mcdonnelldean** [comment]
Only locally for the moment. One of the features I would like to add is a hook into the transport so that each service will send locally and then to other services. Time is my issue unfortunately. I am open to pull requests however if you wanted to take a shot at it :D

**Comment by mananjadhav** [comment]
Sure I can try that. ;)

I am planning to implement a cross-service via gateway (or registry). We're using a basic seneca-transport and the idea is any publish event received to gateway will be served to the listeners on all the services in the registry. Each service will in turn publish this request to all subscribers locally using seneca-pubsub.

What do you think about this?

**Comment by mcdonnelldean** [comment]
Sounds cool! Sure give it a bash on a PR see how it turns out :+1:

**Comment by mananjadhav** [comment]
@mcdonnelldean  Did you get a chance to look into this?

**Comment by frederikheld** [comment]
Hey guys! Is there any chance that this bug will be fixed? I'm experiencing the described error right now, but I see, that there were no updates for this package for 3 years :-( Unfortunately I'm not that experienced with node and seneca that I could provide you with an pull request :-P I would really appreciate your help with this!
